/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as NewInvoiceIndexRouteImport } from './routes/new-invoice/index';
import { Route as settingsLayoutRouteImport } from './routes/(settings)/_layout';
import { Route as homeLayoutRouteImport } from './routes/(home)/_layout';
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up';
import { Route as authLoginRouteImport } from './routes/(auth)/login';
import { Route as homeLayoutIndexRouteImport } from './routes/(home)/_layout.index';
import { Route as InvoicesupdateLayoutRouteImport } from './routes/invoices/(update)/_layout';
import { Route as InvoicesinvoiceLayoutRouteImport } from './routes/invoices/(invoice)/_layout';
import { Route as settingsLayoutSettingsRouteImport } from './routes/(settings)/_layout.settings';
import { Route as InvoicesinvoiceLayoutInvoiceIdRouteImport } from './routes/invoices/(invoice)/_layout.$invoiceId';
import { Route as InvoicesupdateLayoutInvoiceIdUpdateRouteImport } from './routes/invoices/(update)/_layout.$invoiceId.update';

const NewInvoiceIndexRoute = NewInvoiceIndexRouteImport.update({
  id: '/new-invoice/',
  path: '/new-invoice/',
  getParentRoute: () => rootRouteImport,
} as any);
const settingsLayoutRoute = settingsLayoutRouteImport.update({
  id: '/(settings)/_layout',
  getParentRoute: () => rootRouteImport,
} as any);
const homeLayoutRoute = homeLayoutRouteImport.update({
  id: '/(home)/_layout',
  getParentRoute: () => rootRouteImport,
} as any);
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any);
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const homeLayoutIndexRoute = homeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeLayoutRoute,
} as any);
const InvoicesupdateLayoutRoute = InvoicesupdateLayoutRouteImport.update({
  id: '/invoices/(update)/_layout',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any);
const InvoicesinvoiceLayoutRoute = InvoicesinvoiceLayoutRouteImport.update({
  id: '/invoices/(invoice)/_layout',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any);
const settingsLayoutSettingsRoute = settingsLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => settingsLayoutRoute,
} as any);
const InvoicesinvoiceLayoutInvoiceIdRoute = InvoicesinvoiceLayoutInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => InvoicesinvoiceLayoutRoute,
} as any);
const InvoicesupdateLayoutInvoiceIdUpdateRoute =
  InvoicesupdateLayoutInvoiceIdUpdateRouteImport.update({
    id: '/$invoiceId/update',
    path: '/$invoiceId/update',
    getParentRoute: () => InvoicesupdateLayoutRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute;
  '/sign-up': typeof authSignUpRoute;
  '/new-invoice/': typeof NewInvoiceIndexRoute;
  '/settings': typeof settingsLayoutSettingsRoute;
  '/invoices': typeof InvoicesupdateLayoutRouteWithChildren;
  '/': typeof homeLayoutIndexRoute;
  '/invoices/$invoiceId': typeof InvoicesinvoiceLayoutInvoiceIdRoute;
  '/invoices/$invoiceId/update': typeof InvoicesupdateLayoutInvoiceIdUpdateRoute;
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute;
  '/sign-up': typeof authSignUpRoute;
  '/new-invoice': typeof NewInvoiceIndexRoute;
  '/settings': typeof settingsLayoutSettingsRoute;
  '/invoices': typeof InvoicesupdateLayoutRouteWithChildren;
  '/': typeof homeLayoutIndexRoute;
  '/invoices/$invoiceId': typeof InvoicesinvoiceLayoutInvoiceIdRoute;
  '/invoices/$invoiceId/update': typeof InvoicesupdateLayoutInvoiceIdUpdateRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/(auth)/login': typeof authLoginRoute;
  '/(auth)/sign-up': typeof authSignUpRoute;
  '/(home)/_layout': typeof homeLayoutRouteWithChildren;
  '/(settings)/_layout': typeof settingsLayoutRouteWithChildren;
  '/new-invoice/': typeof NewInvoiceIndexRoute;
  '/(settings)/_layout/settings': typeof settingsLayoutSettingsRoute;
  '/invoices/(invoice)/_layout': typeof InvoicesinvoiceLayoutRouteWithChildren;
  '/invoices/(update)/_layout': typeof InvoicesupdateLayoutRouteWithChildren;
  '/(home)/_layout/': typeof homeLayoutIndexRoute;
  '/invoices/(invoice)/_layout/$invoiceId': typeof InvoicesinvoiceLayoutInvoiceIdRoute;
  '/invoices/(update)/_layout/$invoiceId/update': typeof InvoicesupdateLayoutInvoiceIdUpdateRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/login'
    | '/sign-up'
    | '/new-invoice/'
    | '/settings'
    | '/invoices'
    | '/'
    | '/invoices/$invoiceId'
    | '/invoices/$invoiceId/update';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/sign-up'
    | '/new-invoice'
    | '/settings'
    | '/invoices'
    | '/'
    | '/invoices/$invoiceId'
    | '/invoices/$invoiceId/update';
  id:
    | '__root__'
    | '/(auth)/login'
    | '/(auth)/sign-up'
    | '/(home)/_layout'
    | '/(settings)/_layout'
    | '/new-invoice/'
    | '/(settings)/_layout/settings'
    | '/invoices/(invoice)/_layout'
    | '/invoices/(update)/_layout'
    | '/(home)/_layout/'
    | '/invoices/(invoice)/_layout/$invoiceId'
    | '/invoices/(update)/_layout/$invoiceId/update';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  authLoginRoute: typeof authLoginRoute;
  authSignUpRoute: typeof authSignUpRoute;
  homeLayoutRoute: typeof homeLayoutRouteWithChildren;
  settingsLayoutRoute: typeof settingsLayoutRouteWithChildren;
  NewInvoiceIndexRoute: typeof NewInvoiceIndexRoute;
  InvoicesinvoiceLayoutRoute: typeof InvoicesinvoiceLayoutRouteWithChildren;
  InvoicesupdateLayoutRoute: typeof InvoicesupdateLayoutRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-invoice/': {
      id: '/new-invoice/';
      path: '/new-invoice';
      fullPath: '/new-invoice/';
      preLoaderRoute: typeof NewInvoiceIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(settings)/_layout': {
      id: '/(settings)/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof settingsLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(home)/_layout': {
      id: '/(home)/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof homeLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up';
      path: '/sign-up';
      fullPath: '/sign-up';
      preLoaderRoute: typeof authSignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(auth)/login': {
      id: '/(auth)/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof authLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(home)/_layout/': {
      id: '/(home)/_layout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof homeLayoutIndexRouteImport;
      parentRoute: typeof homeLayoutRoute;
    };
    '/invoices/(update)/_layout': {
      id: '/invoices/(update)/_layout';
      path: '/invoices';
      fullPath: '/invoices';
      preLoaderRoute: typeof InvoicesupdateLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/invoices/(invoice)/_layout': {
      id: '/invoices/(invoice)/_layout';
      path: '/invoices';
      fullPath: '/invoices';
      preLoaderRoute: typeof InvoicesinvoiceLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(settings)/_layout/settings': {
      id: '/(settings)/_layout/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof settingsLayoutSettingsRouteImport;
      parentRoute: typeof settingsLayoutRoute;
    };
    '/invoices/(invoice)/_layout/$invoiceId': {
      id: '/invoices/(invoice)/_layout/$invoiceId';
      path: '/$invoiceId';
      fullPath: '/invoices/$invoiceId';
      preLoaderRoute: typeof InvoicesinvoiceLayoutInvoiceIdRouteImport;
      parentRoute: typeof InvoicesinvoiceLayoutRoute;
    };
    '/invoices/(update)/_layout/$invoiceId/update': {
      id: '/invoices/(update)/_layout/$invoiceId/update';
      path: '/$invoiceId/update';
      fullPath: '/invoices/$invoiceId/update';
      preLoaderRoute: typeof InvoicesupdateLayoutInvoiceIdUpdateRouteImport;
      parentRoute: typeof InvoicesupdateLayoutRoute;
    };
  }
}

interface homeLayoutRouteChildren {
  homeLayoutIndexRoute: typeof homeLayoutIndexRoute;
}

const homeLayoutRouteChildren: homeLayoutRouteChildren = {
  homeLayoutIndexRoute: homeLayoutIndexRoute,
};

const homeLayoutRouteWithChildren = homeLayoutRoute._addFileChildren(homeLayoutRouteChildren);

interface settingsLayoutRouteChildren {
  settingsLayoutSettingsRoute: typeof settingsLayoutSettingsRoute;
}

const settingsLayoutRouteChildren: settingsLayoutRouteChildren = {
  settingsLayoutSettingsRoute: settingsLayoutSettingsRoute,
};

const settingsLayoutRouteWithChildren = settingsLayoutRoute._addFileChildren(
  settingsLayoutRouteChildren,
);

interface InvoicesinvoiceLayoutRouteChildren {
  InvoicesinvoiceLayoutInvoiceIdRoute: typeof InvoicesinvoiceLayoutInvoiceIdRoute;
}

const InvoicesinvoiceLayoutRouteChildren: InvoicesinvoiceLayoutRouteChildren = {
  InvoicesinvoiceLayoutInvoiceIdRoute: InvoicesinvoiceLayoutInvoiceIdRoute,
};

const InvoicesinvoiceLayoutRouteWithChildren = InvoicesinvoiceLayoutRoute._addFileChildren(
  InvoicesinvoiceLayoutRouteChildren,
);

interface InvoicesupdateLayoutRouteChildren {
  InvoicesupdateLayoutInvoiceIdUpdateRoute: typeof InvoicesupdateLayoutInvoiceIdUpdateRoute;
}

const InvoicesupdateLayoutRouteChildren: InvoicesupdateLayoutRouteChildren = {
  InvoicesupdateLayoutInvoiceIdUpdateRoute: InvoicesupdateLayoutInvoiceIdUpdateRoute,
};

const InvoicesupdateLayoutRouteWithChildren = InvoicesupdateLayoutRoute._addFileChildren(
  InvoicesupdateLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignUpRoute: authSignUpRoute,
  homeLayoutRoute: homeLayoutRouteWithChildren,
  settingsLayoutRoute: settingsLayoutRouteWithChildren,
  NewInvoiceIndexRoute: NewInvoiceIndexRoute,
  InvoicesinvoiceLayoutRoute: InvoicesinvoiceLayoutRouteWithChildren,
  InvoicesupdateLayoutRoute: InvoicesupdateLayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
